### ISSUE TITLE
"substrings" of long form arguments are "allowed"

### ISSUE THREAD

**Issue by jsivak** [fmenabe/python-clg#4]
Not sure if this is a bug or a feature:

I have a long form argument of "init_sequece" defined in my yaml config.

When I run my program like this:
python program.py --init

the program acts as if "--init-sequence" was fully passed on the commandline. 

Is this expected / desired behavior?

**Comment by fmenabe** [comment]
I don't really like this behaviour so I add an option (``allow_abbrev``) for managing it. It use the tip given at http://bugs.python.org/issue14910 (redefining the ``_get_option_tuples`` method). By default abbrevations are disabled by clg (which is the opposite of argparse).

And thanks for the links!
