### ISSUE TITLE
Adding custom types

### ISSUE THREAD

**Issue by mzdaniel** [fmenabe/python-clg#6]
Hi François and thank you for sharing this package with the community. It is super useful!
I couln't find documentation for adding custom types to the clg/argparse type keyword. and wonder if something like https://github.com/mzdaniel/python-clg/commit/6dbd67409055a52d21f0c158a014e5b6da67a761 might help.

**Comment by fmenabe** [comment]
Hi Daniel! You can already add custom types. You just have to add it to the ``clg.TYPES`` variable. There's an example in the documentation: https://clg.readthedocs.org/en/latest/configuration.html#type. You can also look at the example in the directory *examples/kvm* which use a few custom types. FYI, the configuration file in this example is based on the last version (not yet published on Pypi) which breaks compatibility with previous version if you use groups.

**Comment by mzdaniel** [comment]
This is great! I must have overlook it somehow. And yes, thanks to your comment I looked at the kvm example and after reverting to tag 1.1.1, it runs as designed. Pretty example BTW :)
