### ISSUE TITLE
Combine multiple subparser or spec files.

### ISSUE THREAD

**Issue by Toure** [fmenabe/python-clg#7]
François, thanks for writing this project well done. I have one question in regards to combining multiple spec file is there a programatic way of do this? Example:

```
#! /usr/bin/env python

import clg
import yaml
import yamlordereddictloader

def main():
    cmd = clg.CommandLine(yaml.load(open('Test1.yml'),
                                    Loader=yamlordereddictloader.Loader))
    cmd.append_subparser(yaml.load(open('Test2.yml'),                < ---- mocked method
                                    Loader=yamlordereddictloader.Loader))   < ----
    print(cmd.parse())


if __name__ == '__main__':
    main()
```

> Test1.yml

prog: PROG

options:
    foo:
        action: store_true
        help: foo help

subparsers:
    title: subcommands
    description: valid subcommands
    help: additional help
    prog: SUBCOMMANDS
    metavar: "{METAVAR}"
    parsers:
        a:
            help: a help
            args:
                bar:
                    type: int
                    help: bar help
        b:
            help: b help
            options:
                baz:
                    choices: XYZ
                    help: baz help

> Test2.yml

subparsers:
    title: subcommands
    description: valid subcommands
    help: additional help
    prog: SUBCOMMANDS
    metavar: "{METAVAR}"
    parsers:
        c:
            help: c help
            args:
                car:
                    type: int
                    help: car help
        d:
            help: d help
            options:
                duff:
                    choices: 123
                    help: duff help

**Comment by fmenabe** [comment]
There is nothing in this module for combining files.

The simpler solution would be to merge files before passing it to the CommandLine object.
This can simply be done with something like this:

```python
import yaml
import yamlordereddictloader
from collections import OrderedDict

def yaml_merge(files):
    def merge(dict1, dict2):
        for key, value in dict2.items():
            if key not in dict1:
                dict1[key] = value
            elif isinstance(value, OrderedDict):
                merge(dict1[key], value)

    config = yaml.load(open(files.pop(0)), Loader=yamlordereddictloader.Loader)
    while files:
        merge(config, yaml.load(open(files.pop(0)), Loader=yamlordereddictloader.Loader))
    return config

def main():
    files = [os.path.abspath(filename)
             for filename in os.listdir(sys.path[0])
             if os.path.splitext(filename)[-1] in ('.yml', '.yaml')]
    cmd = clg.CommandLine(yaml_merge(files))
    print(cmd.parse())

if __name__ == '__main__':
    main()
```


I faced the same limitation. To meet this need (and others), I created a small [framework](https://github.com/fmenabe/python-clif). Each command has its own configuration file and the arborescence of subparsers are managed with directories. There's no documentation but if you're curious I pushed an example in the repository.

**Comment by Toure** [comment]
Cool thanks for the info,  will give a try in the morning.

Regards
Touré
